= HiveMQ Kafka Extension Customization SDK

image:https://maven-badges.herokuapp.com/maven-central/com.hivemq/hivemq-kafka-extension-customization-sdk/badge.svg?style=for-the-badge["Maven Central",link="https://maven-badges.herokuapp.com/maven-central/com.hivemq/hivemq-kafka-extension-customization-sdk"]
image:https://javadoc.io/badge2/com.hivemq/hivemq-kafka-extension-customization-sdk/javadoc.svg?style=for-the-badge["javadoc",link=https://javadoc.io/doc/com.hivemq/hivemq-kafka-extension-customization-sdk]

== Features

The HiveMQ Kafka Extension Customization SDK allows the programmatic interaction with the https://www.hivemq.com/extension/hivemq-kafka-extension/[HiveMQ Enterprise Extension for Kafka].

By implementing a customization for the HiveMQ Enterprise Extension for Kafka it is possible to:

* Transform an MQTT PUBLISH into one or multiple Kafka records
* Query the existence of specific Kafka topics
* Create new Kafka topics

== Using the SDK

The HiveMQ Kafka Extension Customization SDK is available in Maven central, so no special configuration is needed.
To use the SDK, add the following dependency to your Maven project:

[source,xml]
----
<dependency>
    <groupId>com.hivemq</groupId>
    <artifactId>hivemq-kafka-extension-customization-sdk</artifactId>
    <version>4.6.7</version>
</dependency>
----

== License

The HiveMQ Kafka Extension SDK is licensed under the `APACHE LICENSE, VERSION 2.0`.
A copy of the license can be found link:LICENSE[here].

== Setup

To be able to use the latest changes of the `hivemq-extension-sdk` please check out the https://github.com/hivemq/hivemq-extension-sdk repository in the same folder as the current project.
(See line `includeBuild("../hivemq-extension-sdk")` in `settings.gradle.kts`).

NOTE: You can also change the path in the `settings.gradle.kts` to the path of your `hivemq-extension-sdk`.

Otherwise, it will not be possible to publish develop snapshots to your local repository.
