= HiveMQ Kafka Extension Customization SDK

image:https://maven-badges.herokuapp.com/maven-central/com.hivemq/hivemq-kafka-extension-customization-sdk/badge.svg["Maven Central",link="https://maven-badges.herokuapp.com/maven-central/com.hivemq/hivemq-kafka-extension-customization-sdk"]
image:https://javadoc.io/badge2/com.hivemq/hivemq-kafka-extension-customization-sdk/javadoc.svg["javadoc", link=https://javadoc.io/doc/com.hivemq/hivemq-kafka-extension-customization-sdk]

== Features

The HiveMQ Kafka Extension Customization SDK allows the programmatic interaction with the https://www.hivemq.com/extension/hivemq-kafka-extension/[HiveMQ Enterprise Extension for Kafka].

By implementing a customization for the HiveMQ Enterprise Extension for Kafka it is possible to:

* Transform an MQTT PUBLISH into one or multiple Kafka records
* Query the existence of specific Kafka topics
* Create new Kafka topics

== Using the SDK

The HiveMQ Kafka Extension Customization SDK is available in Maven central, so no special configuration is needed.
To use the SDK, add the following dependency to your Maven project:

[source,xml]
----
<dependency>
    <groupId>com.hivemq</groupId>
    <artifactId>hivemq-kafka-extension-customization-sdk</artifactId>
    <version>4.4.2</version>
</dependency>
----

== License

The HiveMQ Kafka Extension SDK is licensed under the `APACHE LICENSE, VERSION 2.0`.
A copy of the license can be found link:LICENSE[here].
