[versions]
slf4j = "2.0.7"

[libraries]
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }

[plugins]
nexusPublish = { id = "io.github.gradle-nexus.publish-plugin", version = "1.3.0" }
defaults = { id = "io.github.sgtsilvio.gradle.defaults", version = "0.2.0" }
metadata = { id = "io.github.sgtsilvio.gradle.metadata", version = "0.5.0" }
javadocLinks = { id = "io.github.sgtsilvio.gradle.javadoc-links", version = "0.7.0" }
license = { id = "com.github.hierynomus.license", version = "0.16.1" }
